### ISSUE TITLE
About the code about compliant control in gazebo

### ISSUE THREAD

**Issue by posshe** [cambel/ur3#14]
Hello, cambel:
I'm Hexu, and want to do some research about arm manipulation which needs compliant control. But I don't know how to realize compliant control on the gazebo. Could you please help me to contact with Cristian Camilo Beltran-Hernandez for asking  the code or the part about compliant control in gazebo? Because I can't contact him with this email address "cristianbehe@gmail.org".  The article is "Variable Compliance Control for Robotic Peg-in-Hole Assembly: A Deep Reinforcement Learning Approach".

Thank you very much

Hexu

**Comment by cambel** [comment]
Hi, my contact email is cristianbehe@gmail.com 

Regarding the code, your starting point can be here https://github.com/cambel/ur3/blob/master/ur_control/src/ur_control/compliant_controller.py

I will add a simple example of how to use the compliant control. It works the same for the real robot or in simulation with Gazebo.

**Comment by posshe** [comment]
Thank you for the reply！It's really wonderful job about control and simulator, and I'll close the issue. 
Thank you very much.

**Comment by cambel** [comment]
@posshe see these examples on how to use the compliance controller https://github.com/cambel/ur3/blob/master/ur_control/scripts/compliance_controller_examples.py

You can execute them by first opening the ur3e_cube environment `roslaunch ur3_gazebo ur3e_cubes_example.launch` then executing this new script `rosrun ur_control compliance_controller_examples.py -f`

**Comment by posshe** [comment]
Thank you for the reply. It's really helpful for my work.
