### ISSUE TITLE
How can you deal with mimic in gazebo 9 instead of gazebo 7

### ISSUE THREAD

**Issue by ksjz** [cambel/ur3#17]
heoll, I tested  your project on ROS Melodic Ubuntu 18.04 with Python 3.6.9 
catkin_make,  then there are some problems
![image](https://user-images.githubusercontent.com/38513128/141046118-f8641510-a089-475f-8b45-f83ab7b7d6c0.png)
What can I do to solve this problem? Thank you!

**Comment by cambel** [comment]
Hi @ksjz,

Thanks for testing my project. 

It seems that you are using the wrong version of the robotiq's package. Go to the robotiq-master folder and checkout the `melodic-devel` branch as explained in the [wiki](https://github.com/cambel/ur3/wiki/Compile-from-source-(This-repo))
