### ISSUE TITLE
Can't run scripts Error: package 'ur_control' not found

### ISSUE THREAD

**Issue by ksjz** [cambel/ur3#19]
i have a same issue:   https://github.com/cambel/ur3/issues/11.

Here is  the result of the compilation (catkin build)

--------------------------------------------------------------------------------
Profile:                     default
Extending:             [env] /home/ksjz/ur10e_hande_ws/devel:/home/ksjz/ros_ws/devel:/opt/ros/melodic
Workspace:                   /home/ksjz/ros_ws
--------------------------------------------------------------------------------
Build Space:        [exists] /home/ksjz/ros_ws/build
Devel Space:        [exists] /home/ksjz/ros_ws/devel
Install Space:      [unused] /home/ksjz/ros_ws/install
Log Space:         [missing] /home/ksjz/ros_ws/logs
Source Space:       [exists] /home/ksjz/ros_ws/src
DESTDIR:            [unused] None
--------------------------------------------------------------------------------
Devel Space Layout:          linked
Install Space Layout:        None
--------------------------------------------------------------------------------
Additional CMake Args:       None
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
--------------------------------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
--------------------------------------------------------------------------------
Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.
--------------------------------------------------------------------------------
[build] Found '39' packages in 0.0 seconds.                                    
[build] Updating package table.                                                
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                      [ 1.6 seconds ]       
Starting  >>> controller_stopper                                               
Starting  >>> gazebo_ros_link_attacher                                         
Starting  >>> orocos_kdl                                                       
Starting  >>> robotiq_description                                              
Starting  >>> robotiq_ft_sensor                                                
Starting  >>> robotiq_gazebo                                                   
Starting  >>> robotiq_msgs                                                     
Starting  >>> robotiq_urcap_control                                            
Finished  <<< robotiq_description                        [ 3.7 seconds ]       
_______________________________________________________________________________
Warnings   << robotiq_ft_sensor:cmake /home/ksjz/ros_ws/logs/robotiq_ft_sensor/build.cmake.000.log
CMake Warning (dev) at CMakeLists.txt:54 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "robotiq_ft_sensor_gencfg" of target "rq_test_sensor"
  does not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at CMakeLists.txt:50 (add_dependencies):
  Policy CMP0046 is not set: Error on non-existent dependency in
  add_dependencies.  Run "cmake --help-policy CMP0046" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  The dependency target "robotiq_ft_sensor_gencfg" of target "rq_sensor" does
  not exist.
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/ksjz/ros_ws/build/robotiq_ft_sensor; catkin build --get-env robotiq_ft_sensor | catkin env -si  /usr/bin/cmake /home/ksjz/ros_ws/src/robotiq/robotiq_ft_sensor --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/ksjz/ros_ws/devel/.private/robotiq_ft_sensor -DCMAKE_INSTALL_PREFIX=/home/ksjz/ros_ws/install; cd -
...............................................................................
_______________________________________________________________________________
Warnings   << gazebo_ros_link_attacher:cmake /home/ksjz/ros_ws/logs/gazebo_ros_link_attacher/build.cmake.000.log
CMake Warning (dev) at /usr/share/cmake-3.10/Modules/FindBoost.cmake:911 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "chrono" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /usr/share/OGRE/cmake/modules/FindOGRE.cmake:318 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:175 (find_package)
  CMakeLists.txt:28 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/ksjz/ros_ws/build/gazebo_ros_link_attacher; catkin build --get-env gazebo_ros_link_attacher | catkin env -si  /usr/bin/cmake /home/ksjz/ros_ws/src/gazebo_ros_link_attacher --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/ksjz/ros_ws/devel/.private/gazebo_ros_link_attacher -DCMAKE_INSTALL_PREFIX=/home/ksjz/ros_ws/install; cd -
...............................................................................
Finished  <<< robotiq_urcap_control                      [ 8.8 seconds ]       
_______________________________________________________________________________
Warnings   << robotiq_gazebo:cmake /home/ksjz/ros_ws/logs/robotiq_gazebo/build.cmake.000.log
CMake Warning (dev) at /usr/share/cmake-3.10/Modules/FindBoost.cmake:911 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "chrono" will no longer be dereferenced when the
  policy is set to NEW.  Since the policy is not set the OLD behavior will be
  used.
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindBoost.cmake:1558 (_Boost_MISSING_DEPENDENCIES)
  /usr/share/OGRE/cmake/modules/FindOGRE.cmake:318 (find_package)
  /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake:175 (find_package)
  CMakeLists.txt:11 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

cd /home/ksjz/ros_ws/build/robotiq_gazebo; catkin build --get-env robotiq_gazebo | catkin env -si  /usr/bin/cmake /home/ksjz/ros_ws/src/robotiq/robotiq_gazebo --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/ksjz/ros_ws/devel/.private/robotiq_gazebo -DCMAKE_INSTALL_PREFIX=/home/ksjz/ros_ws/install; cd -
...............................................................................
Finished  <<< controller_stopper                         [ 11.3 seconds ]      
_______________________________________________________________________________
Warnings   << robotiq_ft_sensor:make /home/ksjz/ros_ws/logs/robotiq_ft_sensor/build.make.000.log
In file included from /usr/include/termios.h:25:0,
                 from /home/ksjz/ros_ws/src/robotiq/robotiq_ft_sensor/src/rq_sensor_com.cpp:49:
/usr/include/features.h:184:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
 # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
   ^~~~~~~
cd /home/ksjz/ros_ws/build/robotiq_ft_sensor; catkin build --get-env robotiq_ft_sensor | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Finished  <<< robotiq_ft_sensor                          [ 12.9 seconds ]      
Finished  <<< robotiq_msgs                               [ 14.3 seconds ]      
Starting  >>> trac_ik_lib                                                      
Finished  <<< gazebo_ros_link_attacher                   [ 23.9 seconds ]      
Finished  <<< robotiq_gazebo                             [ 25.0 seconds ]      
Starting  >>> ur_dashboard_msgs                                                
Starting  >>> ur_description                                                   
Starting  >>> ur_e_description                                                 
Starting  >>> ur_handeye_calibration                                           
Starting  >>> ur_kinematics                                                    
Starting  >>> ur_msgs                                                          
_______________________________________________________________________________
Warnings   << orocos_kdl:make /home/ksjz/ros_ws/logs/orocos_kdl/build.make.000.log
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp: In static member function ‘static KDL::Path* KDL::Path::Read(std::istream&)’:
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:81:3: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   auto_ptr<RotationalInterpolation> orient( RotationalInterpolation::Read(is) );
   ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/error_stack.h:42,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:45:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:102:3: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   auto_ptr<RotationalInterpolation> orient( RotationalInterpolation::Read(is) );
   ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/error_stack.h:42,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:45:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:122:3: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   auto_ptr<RotationalInterpolation> orient( RotationalInterpolation::Read(is) );
   ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/error_stack.h:42,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:45:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:123:3: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   auto_ptr<Path_RoundedComposite> tr(
   ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/error_stack.h:42,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:45:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:142:3: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   auto_ptr<Path_Composite> tr( new Path_Composite() );
   ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/error_stack.h:42,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:45:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:155:3: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   auto_ptr<Path> tr( Path::Read(is) );
   ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/error_stack.h:42,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.cpp:45:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_composite.cpp: In member function ‘virtual KDL::Path* KDL::Path_Composite::Clone()’:
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_composite.cpp:113:7: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
  std::auto_ptr<Path_Composite> comp( new Path_Composite() );
       ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/frames_io.hpp:79,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_composite.hpp:48,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_composite.cpp:43:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_roundedcomposite.cpp: In member function ‘void KDL::Path_RoundedComposite::Add(const KDL::Frame&)’:
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_roundedcomposite.cpp:108:9: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
    std::auto_ptr < Path
         ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/frames_io.hpp:79,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.hpp:51,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_roundedcomposite.hpp:47,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_roundedcomposite.cpp:43:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_roundedcomposite.cpp:112:9: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
    std::auto_ptr < Path
         ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/frames_io.hpp:79,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path.hpp:51,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_roundedcomposite.hpp:47,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/path_roundedcomposite.cpp:43:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp: In static member function ‘static KDL::Trajectory* KDL::Trajectory::Read(std::istream&)’:
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:65:3: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   auto_ptr<Path>      geom(    Path::Read(is)       );
   ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/error_stack.h:42,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:44:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
/home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:66:3: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
   auto_ptr<VelocityProfile> motprof( VelocityProfile::Read(is)  );
   ^~~~~~~~
In file included from /usr/include/c++/7/bits/locale_conv.h:41:0,
                 from /usr/include/c++/7/locale:43,
                 from /usr/include/c++/7/iomanip:43,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/utility_io.h:28,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/utilities/error_stack.h:42,
                 from /home/ksjz/ros_ws/src/ur3/docker/orocos_kinematics_dynamics/orocos_kdl/src/trajectory.cpp:44:
/usr/include/c++/7/bits/unique_ptr.h:51:28: note: declared here
   template<typename> class auto_ptr;
                            ^~~~~~~~
cd /home/ksjz/ros_ws/build/orocos_kdl; catkin build --get-env orocos_kdl | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Finished  <<< orocos_kdl                                 [ 32.4 seconds ]      
Starting  >>> ur_pykdl                                                         
_______________________________________________________________________________
Errors     << trac_ik_lib:make /home/ksjz/ros_ws/logs/trac_ik_lib/build.make.000.log
/usr/bin/ld: cannot find -lnlopt_cxx
collect2: error: ld returned 1 exit status
make[2]: *** [/home/ksjz/ros_ws/devel/.private/trac_ik_lib/lib/libtrac_ik.so] Error 1
make[1]: *** [CMakeFiles/trac_ik.dir/all] Error 2
make: *** [all] Error 2
cd /home/ksjz/ros_ws/build/trac_ik_lib; catkin build --get-env trac_ik_lib | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << trac_ik_lib:make                           [ Exited with code 2 ]
Failed    <<< trac_ik_lib                                [ 21.7 seconds ]      
Abandoned <<< ur3_description                            [ Unrelated job failed ]
Abandoned <<< robotiq_control                            [ Unrelated job failed ]
Abandoned <<< python_orocos_kdl                          [ Unrelated job failed ]
Abandoned <<< orocos_kinematics_dynamics                 [ Unrelated job failed ]
Abandoned <<< trac_ik_examples                           [ Unrelated job failed ]
Abandoned <<< trac_ik_kinematics_plugin                  [ Unrelated job failed ]
Abandoned <<< trac_ik_python                             [ Unrelated job failed ]
Abandoned <<< ur3_gazebo                                 [ Unrelated job failed ]
Abandoned <<< ur_control                                 [ Unrelated job failed ]
Abandoned <<< ur10_moveit_config                         [ Unrelated job failed ]
Abandoned <<< ur10e_moveit_config                        [ Unrelated job failed ]
Abandoned <<< ur16e_moveit_config                        [ Unrelated job failed ]
Abandoned <<< ur3_moveit_config                          [ Unrelated job failed ]
Abandoned <<< ur3e_moveit_config                         [ Unrelated job failed ]
Abandoned <<< ur5_moveit_config                          [ Unrelated job failed ]
Abandoned <<< ur5e_moveit_config                         [ Unrelated job failed ]
Abandoned <<< ur_gazebo                                  [ Unrelated job failed ]
Abandoned <<< ur_gripper_85_moveit_config                [ Unrelated job failed ]
Abandoned <<< ur_hande_moveit_config                     [ Unrelated job failed ]
Abandoned <<< ur_robot_driver                            [ Unrelated job failed ]
Abandoned <<< ur_calibration                             [ Unrelated job failed ]
Finished  <<< ur_description                             [ 5.2 seconds ]       
Finished  <<< ur_e_description                           [ 4.9 seconds ]       
Finished  <<< ur_handeye_calibration                     [ 5.1 seconds ]       
Finished  <<< ur_pykdl                                   [ 6.8 seconds ]       
Finished  <<< ur_dashboard_msgs                          [ 17.4 seconds ]      
Finished  <<< ur_msgs                                    [ 10.8 seconds ]      
_______________________________________________________________________________
Warnings   << ur_kinematics:make /home/ksjz/ros_ws/logs/ur_kinematics/build.make.000.log
In file included from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:75:0:
/opt/ros/melodic/include/class_loader/class_loader.h:36:2: warning: #warning Including header <class_loader/class_loader.h> is deprecated, include <class_loader/class_loader.hpp> instead. [-Wcpp]
 #warning Including header <class_loader/class_loader.h> is deprecated, \
  ^~~~~~~
In file included from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:75:0:
/opt/ros/melodic/include/class_loader/class_loader.h:36:2: warning: #warning Including header <class_loader/class_loader.h> is deprecated, include <class_loader/class_loader.hpp> instead. [-Wcpp]
 #warning Including header <class_loader/class_loader.h> is deprecated, \
  ^~~~~~~
In file included from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:75:0:
/opt/ros/melodic/include/class_loader/class_loader.h:36:2: warning: #warning Including header <class_loader/class_loader.h> is deprecated, include <class_loader/class_loader.hpp> instead. [-Wcpp]
 #warning Including header <class_loader/class_loader.h> is deprecated, \
  ^~~~~~~
/home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp: In member function ‘virtual bool ur_kinematics::URKinematicsPlugin::initialize(const string&, const string&, const string&, const string&, double)’:
/home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:174:88: warning: ‘virtual void kinematics::KinematicsBase::setValues(const string&, const string&, const string&, const string&, double)’ is deprecated [-Wdeprecated-declarations]
   setValues(robot_description, group_name, base_frame, tip_frame, search_discretization);
                                                                                        ^
In file included from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/include/ur_kinematics/ur_moveit_plugin.h:100:0,
                 from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:88:
/opt/ros/melodic/include/moveit/kinematics_base/kinematics_base.h:344:31: note: declared here
   [[deprecated]] virtual void setValues(const std::string& robot_description, const std::string& group_name,
                               ^~~~~~~~~
/home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp: In member function ‘virtual bool ur_kinematics::URKinematicsPlugin::initialize(const string&, const string&, const string&, const string&, double)’:
/home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:174:88: warning: ‘virtual void kinematics::KinematicsBase::setValues(const string&, const string&, const string&, const string&, double)’ is deprecated [-Wdeprecated-declarations]
   setValues(robot_description, group_name, base_frame, tip_frame, search_discretization);
                                                                                        ^
In file included from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/include/ur_kinematics/ur_moveit_plugin.h:100:0,
                 from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:88:
/opt/ros/melodic/include/moveit/kinematics_base/kinematics_base.h:344:31: note: declared here
   [[deprecated]] virtual void setValues(const std::string& robot_description, const std::string& group_name,
                               ^~~~~~~~~
/home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp: In member function ‘virtual bool ur_kinematics::URKinematicsPlugin::initialize(const string&, const string&, const string&, const string&, double)’:
/home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:174:88: warning: ‘virtual void kinematics::KinematicsBase::setValues(const string&, const string&, const string&, const string&, double)’ is deprecated [-Wdeprecated-declarations]
   setValues(robot_description, group_name, base_frame, tip_frame, search_discretization);
                                                                                        ^
In file included from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/include/ur_kinematics/ur_moveit_plugin.h:100:0,
                 from /home/ksjz/ros_ws/src/universal_robot/ur_kinematics/src/ur_moveit_plugin.cpp:88:
/opt/ros/melodic/include/moveit/kinematics_base/kinematics_base.h:344:31: note: declared here
   [[deprecated]] virtual void setValues(const std::string& robot_description, const std::string& group_name,
                               ^~~~~~~~~
cd /home/ksjz/ros_ws/build/ur_kinematics; catkin build --get-env ur_kinematics | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Finished  <<< ur_kinematics                              [ 14.9 seconds ]      
[build] Summary: 16 of 38 packages succeeded.                                  
[build]   Ignored:   2 packages were skipped or are blacklisted.               
[build]   Warnings:  5 packages succeeded with warnings.                       
[build]   Abandoned: 21 packages were abandoned.                               
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 48.7 seconds total.                                           
[build] Note: Workspace packages have changed, please re-source setup files to use them.

**Comment by ksjz** [comment]
in addition: 
 in ur3/docker folder, there is no launch_docker.sh
Is this the cause of the compilation problem?

**Comment by cambel** [comment]
Hi, it seems you have a problem compiling `trac_ik_lib` shown here in your trace:
```
Errors << trac_ik_lib:make /home/ksjz/ros_ws/logs/trac_ik_lib/build.make.000.log
/usr/bin/ld: cannot find -lnlopt_cxx
collect2: error: ld returned 1 exit status
make[2]: *** [/home/ksjz/ros_ws/devel/.private/trac_ik_lib/lib/libtrac_ik.so] Error 1
make[1]: *** [CMakeFiles/trac_ik.dir/all] Error 2
make: *** [all] Error 2
```
I am not sure why though. I would suggest trying to update the ros dependencies using the following commands from the workspace directory:
```
rosdep fix-permissions
rosdep update -q
rosdep install --from-paths src --ignore-src --rosdistro=$ROS_DISTRO -y
```
