### ISSUE TITLE
[ WARN] ： The complete state of the robot is not yet known.  Missing hande_left_finger_joint

### ISSUE THREAD

**Issue by NIU55666** [cambel/ur3#28]
When I run `roslaunch ur_hande_moveit_config start_moveit.launch`, a warning appears: "The complete state of the robot is not yet known. Missing hande_left_finger_joint." It keeps popping up. How can I resolve this?

**Comment by cambel** [comment]
@NIU55666 
What version of ROS are you working on?
Are you using docker or installing from source?

**Comment by NIU55666** [comment]
> 



> @NIU55666 What version of ROS are you working on? Are you using docker or installing from source?

My ROS version is Noetic. I'm not using Docker; I'm installing it from source.

**Comment by cambel** [comment]
@NIU55666 

I can't reproduce what you described. Can you provide more information on what you are trying to do and the trace from the terminal?

Also, make sure that you are on the latest commit of the robotiq package.
I uploaded some changes to this `ur3` repo, you may consider reinstalling/building it

**Comment by NIU55666** [comment]
> @NIU55666
> 
> I can't reproduce what you described. Can you provide more information on what you are trying to do and the trace from the terminal?
> 
> Also, make sure that you are on the latest commit of the robotiq package. I uploaded some changes to this `ur3` repo, you may consider reinstalling/building it

Thank you very much, I have solved this problem, I used to build the workspace with catkin_make, and later I used catkin build without this warning.
